//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1QA.Core.Csharp.White.UIElement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A1QA.Core.Csharp.White.UIElement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : UIItem [AutomationId:{1}] [Name:{2}] [Type:{3}].
        /// </summary>
        internal static string AcceptanceCriteriaMsg {
            get {
                return ResourceManager.GetString("AcceptanceCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Value &apos;{1}&apos; : UIItem [AutomationId:{2}] [Name:{3}] [Type:{4}].
        /// </summary>
        internal static string AcceptanceCriteriaValueMsg {
            get {
                return ResourceManager.GetString("AcceptanceCriteriaValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching Application to existing process [ProcessName:{0}]....
        /// </summary>
        internal static string ApplicationAttachMsg {
            get {
                return ResourceManager.GetString("ApplicationAttachMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Application [ProcessName:{0}]....
        /// </summary>
        internal static string ApplicationCloseMsg {
            get {
                return ResourceManager.GetString("ApplicationCloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closed!.
        /// </summary>
        internal static string ApplicationCloseSuccessMsg {
            get {
                return ResourceManager.GetString("ApplicationCloseSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to launch! : {0}.
        /// </summary>
        internal static string ApplicationLaunchFailureMsg {
            get {
                return ResourceManager.GetString("ApplicationLaunchFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Application : &apos;{0}&apos;.
        /// </summary>
        internal static string ApplicationLaunchMsg {
            get {
                return ResourceManager.GetString("ApplicationLaunchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application launched in {0} seconds.
        /// </summary>
        internal static string ApplicationLaunchSuccessMsg {
            get {
                return ResourceManager.GetString("ApplicationLaunchSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different values at &apos;Row: {0}, Column: {1}&apos;. Expected &apos;{2}&apos;, Actual &apos;{3}&apos;.
        /// </summary>
        internal static string DataGridDifferentValueMsg {
            get {
                return ResourceManager.GetString("DataGridDifferentValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CheckBox &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyCheckBoxSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyCheckBoxSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSelected CheckBox &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyCheckBoxUnSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyCheckBoxUnSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox &apos;{0}&apos; is not editable.
        /// </summary>
        internal static string FriendlyComboBoxNotEditable {
            get {
                return ResourceManager.GetString("FriendlyComboBoxNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ComboBox &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string FriendlyComboBoxSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyComboBoxSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Cell &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string FriendlyDataGridCellSetMsg {
            get {
                return ResourceManager.GetString("FriendlyDataGridCellSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; passed comparison check.
        /// </summary>
        internal static string FriendlyDataGridComparePassMsg {
            get {
                return ResourceManager.GetString("FriendlyDataGridComparePassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; matches row count of expected table.
        /// </summary>
        internal static string FriendlyDataGridCompareRowCountMsg {
            get {
                return ResourceManager.GetString("FriendlyDataGridCompareRowCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Row &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyDataGridRowSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyDataGridRowSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked ListItem &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyListItemCheckMsg {
            get {
                return ResourceManager.GetString("FriendlyListItemCheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected ListItem &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyListItemSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyListItemSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnChecked ListItem &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyListItemUnCheckMsg {
            get {
                return ResourceManager.GetString("FriendlyListItemUnCheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select table row &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyTableRowSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyTableRowSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tab &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyTabSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyTabSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Field &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string FriendlyTextBoxSetMsg {
            get {
                return ResourceManager.GetString("FriendlyTextBoxSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TreeNode &apos;{0}&apos;.
        /// </summary>
        internal static string FriendlyTreeNodeSelectMsg {
            get {
                return ResourceManager.GetString("FriendlyTreeNodeSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : ListItem with label &apos;{0}&apos; was not found in &apos;{1}&apos; ListBox parent.
        /// </summary>
        internal static string ListBoxItemNotFoundErrorMsg {
            get {
                return ResourceManager.GetString("ListBoxItemNotFoundErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if Modal Window exists....
        /// </summary>
        internal static string ModalWindowExistsMsg {
            get {
                return ResourceManager.GetString("ModalWindowExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Modal Window matching [SearchCriteria:{0}] in Window [AutomationId:{1}]....
        /// </summary>
        internal static string ModalWindowFindUsingSearchCriteriaMsg {
            get {
                return ResourceManager.GetString("ModalWindowFindUsingSearchCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Modal Window matching [Title:{0}] in Window [AutomationId:{1}]....
        /// </summary>
        internal static string ModalWindowFindUsingTitleMsg {
            get {
                return ResourceManager.GetString("ModalWindowFindUsingTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Window found in {0} seconds.
        /// </summary>
        internal static string ModalWindowFoundMsg {
            get {
                return ResourceManager.GetString("ModalWindowFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Window is off-screen!.
        /// </summary>
        internal static string ModalWindowIsOffScreenMsg {
            get {
                return ResourceManager.GetString("ModalWindowIsOffScreenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Window not found within {0} timeout! : {1}.
        /// </summary>
        internal static string ModalWindowNotFoundMsg {
            get {
                return ResourceManager.GetString("ModalWindowNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : TreeNode with path &apos;{0}&apos; was not found in &apos;{1}&apos; Tree parent.
        /// </summary>
        internal static string TreeNodeNotFoundErrorMsg {
            get {
                return ResourceManager.GetString("TreeNodeNotFoundErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : UIItem [FriendlyName:{1}] [AutomationId:{2}] [Name:{3}] [Type:{4}].
        /// </summary>
        internal static string UIItemActionMsg {
            get {
                return ResourceManager.GetString("UIItemActionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Value &apos;{1}&apos; : UIItem [FriendlyName:{2}] [AutomationId:{3}] [Name:{4}] [Type:{5}].
        /// </summary>
        internal static string UIItemActionValueMsg {
            get {
                return ResourceManager.GetString("UIItemActionValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking UIItem [AutomationId:{0}] [Name:{1}] also matches ExtraCriteria....
        /// </summary>
        internal static string UIItemCheckUsingExtraCriteriaMsg {
            get {
                return ResourceManager.GetString("UIItemCheckUsingExtraCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug : UIItem [AutomationId:{0}] [Name:{1}] [Type:{2}].
        /// </summary>
        internal static string UIItemDebugMsg {
            get {
                return ResourceManager.GetString("UIItemDebugMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem does not exist! : {0}.
        /// </summary>
        internal static string UIItemExistsFalseMsg {
            get {
                return ResourceManager.GetString("UIItemExistsFalseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if UIItem exists....
        /// </summary>
        internal static string UIItemExistsMsg {
            get {
                return ResourceManager.GetString("UIItemExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem does exist but is off-screen! : UIItem [AutomationId:{0}] [Name:{1}] [Type:{2}].
        /// </summary>
        internal static string UIItemExistsOffScreenMsg {
            get {
                return ResourceManager.GetString("UIItemExistsOffScreenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem does exist : UIItem [AutomationId:{0}] [Name:{1}] [Type:{2}].
        /// </summary>
        internal static string UIItemExistsTrueMsg {
            get {
                return ResourceManager.GetString("UIItemExistsTrueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding UIItem matching [Condition:{0}] [Type:{1}] [TreeScope:{2}] in Scope [AutomationId:{3}]....
        /// </summary>
        internal static string UIItemFindUsingConditionMsg {
            get {
                return ResourceManager.GetString("UIItemFindUsingConditionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding UIItem matching [SearchCriteria:{0}] [Type:{1}] [ExtraCriteria:{2}={3}] in Scope [AutomationId:{4}]....
        /// </summary>
        internal static string UIItemFindUsingExtraCriteriaMsg {
            get {
                return ResourceManager.GetString("UIItemFindUsingExtraCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding UIItem matching [SearchCriteria:{0}] [Type:{1}] in Scope [AutomationId:{2}]....
        /// </summary>
        internal static string UIItemFindUsingSearchCriteriaMsg {
            get {
                return ResourceManager.GetString("UIItemFindUsingSearchCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem found in {0} seconds.
        /// </summary>
        internal static string UIItemFoundMsg {
            get {
                return ResourceManager.GetString("UIItemFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast on UIItem! : {0}.
        /// </summary>
        internal static string UIItemInvalidCastMsg {
            get {
                return ResourceManager.GetString("UIItemInvalidCastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem is null! : [FriendlyName: {0}].
        /// </summary>
        internal static string UIItemIsNullMsg {
            get {
                return ResourceManager.GetString("UIItemIsNullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding *multiple* UIItems matching in Scope [AutomationId:{0}]....
        /// </summary>
        internal static string UIItemMultipleFindUsingAutomationPropertyCriteriaMsg {
            get {
                return ResourceManager.GetString("UIItemMultipleFindUsingAutomationPropertyCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding *multiple* UIItems matching [SearchCriteria:{0}] [Type:{1}] in Scope [AutomationId:{2}]....
        /// </summary>
        internal static string UIItemMultipleFindUsingSearchCriteriaMsg {
            get {
                return ResourceManager.GetString("UIItemMultipleFindUsingSearchCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} UIItem(s) found in {1} seconds.
        /// </summary>
        internal static string UIItemMultipleFoundMsg {
            get {
                return ResourceManager.GetString("UIItemMultipleFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem(s) not found within {0} timeout! : {1}.
        /// </summary>
        internal static string UIItemMultipleNotFoundMsg {
            get {
                return ResourceManager.GetString("UIItemMultipleNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIItem not found within {0} timeout! : {1}.
        /// </summary>
        internal static string UIItemNotFoundMsg {
            get {
                return ResourceManager.GetString("UIItemNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Window [WindowName={0}]....
        /// </summary>
        internal static string WindowCloseMsg {
            get {
                return ResourceManager.GetString("WindowCloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window does not exist! : {0}.
        /// </summary>
        internal static string WindowExistsFalseMsg {
            get {
                return ResourceManager.GetString("WindowExistsFalseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if Window exists....
        /// </summary>
        internal static string WindowExistsMsg {
            get {
                return ResourceManager.GetString("WindowExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window does exist but is off-screen! : UIItem [AutomationId:{0}] [Name:{1}].
        /// </summary>
        internal static string WindowExistsOffScreenMsg {
            get {
                return ResourceManager.GetString("WindowExistsOffScreenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window does exist : Window [AutomationId:{0}] [Name:{1}].
        /// </summary>
        internal static string WindowExistsTrueMsg {
            get {
                return ResourceManager.GetString("WindowExistsTrueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Window matching [SearchCriteria:{0}] in Application [ProcessName:{1}]....
        /// </summary>
        internal static string WindowFindUsingSearchCriteriaMsg {
            get {
                return ResourceManager.GetString("WindowFindUsingSearchCriteriaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window found in {0} seconds.
        /// </summary>
        internal static string WindowFoundMsg {
            get {
                return ResourceManager.GetString("WindowFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window is null!.
        /// </summary>
        internal static string WindowIsNullMsg {
            get {
                return ResourceManager.GetString("WindowIsNullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximizing Window [WindowName={0}]....
        /// </summary>
        internal static string WindowMaximizeMsg {
            get {
                return ResourceManager.GetString("WindowMaximizeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window not found within {0} timeout! : {1}.
        /// </summary>
        internal static string WindowNotFoundMsg {
            get {
                return ResourceManager.GetString("WindowNotFoundMsg", resourceCulture);
            }
        }
    }
}
