//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1QA.Core.Csharp.White.Basics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultFriendlyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultFriendlyMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A1QA.Core.Csharp.White.Basics.Resources.DefaultFriendlyMessage", typeof(DefaultFriendlyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that &apos;{0}&apos; and &apos;{1}&apos; (actual value) are Equal..
        /// </summary>
        public static string AssertAreEqual {
            get {
                return ResourceManager.GetString("AssertAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that &apos;{0}&apos; and &apos;{1}&apos; (actual value) are not Equal..
        /// </summary>
        public static string AssertAreNotEqual {
            get {
                return ResourceManager.GetString("AssertAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that collection with count &apos;{0}&apos; and &apos;{1}&apos; (actual collection count) are Equal..
        /// </summary>
        public static string AssertCollectionsAreEqual {
            get {
                return ResourceManager.GetString("AssertCollectionsAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that string &apos;{0}&apos; contains &apos;{1}&apos; substring..
        /// </summary>
        public static string AssertContains {
            get {
                return ResourceManager.GetString("AssertContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that string &apos;{0}&apos; does not contain &apos;{1}&apos; substring..
        /// </summary>
        public static string AssertDoesNotContain {
            get {
                return ResourceManager.GetString("AssertDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that &apos;{0}&apos; is False..
        /// </summary>
        public static string AssertIsFalse {
            get {
                return ResourceManager.GetString("AssertIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; is greater than &apos;{0}&apos;..
        /// </summary>
        public static string AssertIsGreater {
            get {
                return ResourceManager.GetString("AssertIsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; is greater than &apos;{0}&apos; or equal..
        /// </summary>
        public static string AssertIsGreaterOrEqual {
            get {
                return ResourceManager.GetString("AssertIsGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; is less than &apos;{0}&apos;..
        /// </summary>
        public static string AssertIsLess {
            get {
                return ResourceManager.GetString("AssertIsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; is less than &apos;{0}&apos; or equal..
        /// </summary>
        public static string AssertIsLessOrEqual {
            get {
                return ResourceManager.GetString("AssertIsLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; value is not Null..
        /// </summary>
        public static string AssertIsNotNull {
            get {
                return ResourceManager.GetString("AssertIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that the &apos;{0}&apos; value is Null..
        /// </summary>
        public static string AssertIsNull {
            get {
                return ResourceManager.GetString("AssertIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that &apos;{0}&apos; is True..
        /// </summary>
        public static string AssertIsTrue {
            get {
                return ResourceManager.GetString("AssertIsTrue", resourceCulture);
            }
        }
    }
}
